apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "runtime.fullname" . }}-entrypoint
  annotations:
    kubernetes.io/ingress.class: "nginx"
    {{ if .Values.entrypointTLS }}
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: clusterissuer-runtimes-entrypoints
    {{ end }}
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    # Based on this snippet:
    #  https://github.com/kubernetes/ingress-nginx/issues/5609#issuecomment-634908849
    nginx.ingress.kubernetes.io/server-snippet: |
      error_page 404 = @grpc_unimplemented;
      error_page 502 503 = @grpc_unavailable;

      location @grpc_unimplemented {
          add_header grpc-status 12;
          add_header grpc-message unimplemented;
          return 204;
      }
      location @grpc_unavailable {
          add_header grpc-status 14;
          add_header grpc-message unavailable;
          return 204;
      }
      default_type application/grpc;

spec:
  {{ if .Values.entrypointTLS -}}
  tls:
    - hosts:
        - entrypoint.{{ .Values.host }}
      secretName: entrypoint.{{ .Values.host }}-tls
  {{ end -}}
  rules:
    - host: entrypoint.{{ .Values.host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: active-entrypoint
              servicePort: grpc
