baseDomainName: "local"
admin:
  apiAddress: ":4000"
  baseURL: "http://api.kre.local"
  frontendBaseURL: "http://admin.kre.local"
  corsEnabled: true
  storagePath: /admin-api-files
smtp:
  enabled: false
auth:
  verificationCodeDurationInMinutes: 1
  jwtSignSecret: "jwt_secret"
  secureCookie: false
  cookieDomain: "kre.local"
mongodb:
  address: "mongodb://admin:123456@mongodb:27017/localKRE"
  dbName: "localKRE"
services:
  k8sManager: "localhost:50051"
