apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "runtime.fullname" . }}-entrypoint-web
  annotations:
    kubernetes.io/ingress.class: "nginx"
    {{ if .Values.entrypointTLS }}
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: clusterissuer-runtimes-entrypoints
    {{ end }}
    nginx.ingress.kubernetes.io/default-backend: runtime-default-backend
    nginx.ingress.kubernetes.io/custom-http-errors: "404,503,502"
spec:
  {{ if .Values.entrypointTLS -}}
  tls:
  - hosts: 
    - proto.{{ .Values.runtime.host }}
    secretName: entrypoint.{{ .Values.runtime.host }}-tls
  {{ end -}}
  rules:
    - host: proto.{{ .Values.runtime.host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: active-entrypoint
              servicePort: web
