release-kre-entrypoint:
  stage: semantic-release
  image: node:10
  before_script:
    - npm install --prefix runners/kre-entrypoint
  script:
    - cd runners/kre-entrypoint && npx semantic-release
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always
      changes:
        - runners/kre-entrypoint/**/*
        - .gitlab-ci.yml

publish-kre-entrypoint-image:
  stage: publish-image
  image: docker:18-git
  services:
    - docker:18-dind
  variables:
    IMAGE_PROJECT_NAME: "konstellation/kre-runtime-entrypoint"
    DOCKER_USER: $DOCKER_USER
    DOCKER_PASS: $DOCKER_PASS
  before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
  script:
    - TAG=${CI_COMMIT_TAG#kre-entrypoint-v}
    - docker build -t $IMAGE_PROJECT_NAME:$TAG runners/kre-entrypoint
    - docker tag $IMAGE_PROJECT_NAME:$TAG $IMAGE_PROJECT_NAME:latest
    - docker push $IMAGE_PROJECT_NAME:$TAG
    - docker push $IMAGE_PROJECT_NAME:latest
  rules:
    - if: '$CI_COMMIT_TAG =~ /^kre-entrypoint-v\d*.\d*.\d*$/'
      when: always
