{{- if .Values.certManager.enabled }}
apiVersion: cert-manager.io/v1alpha3
kind: Issuer
metadata:
  name: {{ template "kre.fullname" . }}-admin-ui
spec:
  acme:
    server: {{ .Values.certManager.acme.server }}
    email: {{ .Values.certManager.acme.email }}
    privateKeySecretRef:
      name: {{ template "kre.fullname" . }}-admin-ui
    solvers:
      {{ if hasKey .Values.certManager "dns01" -}}
      - dns01:
          route53:
            region: {{ .Values.certManager.dns01.route53.region }}
            accessKeyID: {{ .Values.certManager.dns01.route53.accessKeyID }}
            hostedZoneID: {{ .Values.certManager.dns01.route53.hostedZoneID }}
            secretAccessKeySecretRef:
              name: aws-secret
              key: AWS_SECRET_ACCESS_KEY
    {{ else -}}
      - http01:
          ingress:
            class: nginx
    {{ end -}}
{{- end }}
