developmentMode: false

entrypoint:
  host: "local"

sharedStorageClass: standard

nats_streaming:
  replicas: 1
  storage:
    className: standard
    size: 1Gi

mongo:
  replicas: 3
  replicaSetName: rs0
  image:
    tag: 4.2
  securityContext:
    enabled: false
  persistentVolume:
    enabled: true
    storageClass: standard
    size: 5Gi
  auth:
    enabled: true
    key: "qwerlk12SDf"
    adminUser: "admin"
    adminPassword: "123456"
  extraLabels:
    kre-app: kre-mongo

minio:
  credentials:
    accessKey: admin
    secretKey: "12345678"
  storage:
    size: 1Gi
