admin:
  apiAddress: ":4000"
  frontendBaseURL: "http://localhost:3000"
  corsEnabled: true
smtp:
  enabled: false
auth:
  verificationCodeDurationInMinutes: 1
  jwtSignSecret: "jwt_secret"
  secureCookie: false
mongodb:
  address: "mongodb://admin:123456@mongodb:27017/localKRE"
  dbName: "localKRE"
services:
  k8sManager: "localhost:50051"
