apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "runtime.fullname" . }}-entrypoint
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
spec:
  rules:
    - host: {{ .Values.entrypoint.host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: active-entrypoint
              servicePort: grpc