{{ if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1" }}
apiVersion: networking.k8s.io/v1beta1
{{ else if .Capabilities.APIVersions.Has "extensions/v1beta1" }}
apiVersion: extensions/v1beta1
{{ end }}
kind: Ingress
metadata:
  name: {{ template "kre.fullname" . }}-admin-api-ingress
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: {{ template "kre.fullname" . }}-admin-api
    {{ if hasKey .Values.certManager "dns01" -}}
    cert-manager.io/acme-challenge-type: "dns01"
    {{ else -}}
    cert-manager.io/acme-challenge-type: "http01"
    {{ end }}
    nginx.ingress.kubernetes.io/proxy-body-size: 100000m
  labels:
    {{- include "kre.labels" . | nindent 4 }}
    app:  {{ template "kre.fullname" . }}-admin-api-ingress
spec:
  {{- if .Values.adminApi.tls.enabled }}
  tls:
  - hosts: 
    - {{ .Values.adminApi.host }}
    secretName: {{ .Values.adminApi.host }}-tls
  {{- end }}
  rules:
    - host: {{ .Values.adminApi.host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: admin-api
              servicePort: {{ .Values.adminApi.service.port }}
