{{ if .Capabilities.APIVersions.Has "apps/v1" }}
apiVersion: apps/v1
  {{ else if .Capabilities.APIVersions.Has "extensions/v1beta1" }}
apiVersion: extensions/v1beta1
  {{ end }}
kind: Deployment
metadata:
  name: runtime-api
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "runtime.labels" . | nindent 6 }}
      app: runtime-api
  template:
    metadata:
      labels:
        {{- include "runtime.labels" . | nindent 8 }}
        app: runtime-api
    spec:
      containers:
        - name: runtime-api
          # TODO: This version should be fixed and the operator released in-sync with new runtime-api changes
          image: konstellation/kre-runtime-api:latest
          imagePullPolicy: {{ if .Values.developmentMode }}IfNotPresent{{ else }}Always{{ end }}
          ports:
            - containerPort: 50051
              protocol: TCP
              name: grpc
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KRE_SHARED_STORAGECLASS
              value: {{ .Values.runtime.sharedStorageClass }}
            - name: KRE_RUNTIME_API_SERVER_PORT
              value: "50051"
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-runtime-secrets
