test-admin-ui:
  stage: test
  image: node:14
  before_script:
    - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
    - apt update && apt install yarn -y
    - cd admin/admin-ui
    - yarn install
  script:
    - yarn run test:cov:ci
    - yarn run test:cov:sonar
  coverage: '/Statements   : \d+\.\d+/'
  artifacts:
    paths:
      - admin/admin-ui/test-report.xml
    reports:
      junit: admin/admin-ui/junit.xml
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always
      changes:
        - admin/admin-ui/**/*

sonar-admin-ui:
  extends: .sonar-scanner
  variables:
    SONAR_TOKEN: $SONAR_TOKEN_ADMIN_UI
    SONAR_USER_HOME: '${CI_PROJECT_DIR}/admin-ui/.sonar'
    COMPONENT_PATH: admin-ui
    GIT_DEPTH: '0'
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always
      changes:
        - admin/admin-ui/**/*

release-admin-ui:
  stage: semantic-release
  image: node:10
  before_script:
    - npm install --prefix admin/admin-ui
  script:
    - cd admin/admin-ui && npx semantic-release -e semantic-release-monorepo
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always
      changes:
        - admin/admin-ui/**/*

publish-admin-ui-image:
  stage: publish-image
  image: docker:18-git
  services:
    - docker:18-dind
  variables:
    IMAGE_PROJECT_NAME: 'konstellation/kre-admin-ui'
    DOCKER_USER: $DOCKER_USER
    DOCKER_PASS: $DOCKER_PASS
  before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
  script:
    - TAG=${CI_COMMIT_TAG#admin-ui-v}
    - docker build -t $IMAGE_PROJECT_NAME:$TAG admin/admin-ui
    - docker tag $IMAGE_PROJECT_NAME:$TAG $IMAGE_PROJECT_NAME:latest
    - docker push $IMAGE_PROJECT_NAME:$TAG
    - docker push $IMAGE_PROJECT_NAME:latest
  rules:
    - if: '$CI_COMMIT_TAG =~ /^admin-ui-v\d*.\d*.\d*$/'
      when: always
