{{- if .Values.developmentMode }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-admin-ui-ingress
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: {{ .Release.Name }}-admin-ui
    {{ if hasKey .Values.certManager "dns01" -}}
    cert-manager.io/acme-challenge-type: "dns01"
    {{ else -}}
    cert-manager.io/acme-challenge-type: "http01"
    {{ end }}
  labels:
    {{- include "kre.labels" . | nindent 4 }}
    app: {{ .Release.Name }}-admin-ui-ingress
spec:
  {{- if .Values.adminUI.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.adminUI.host }}
      secretName: {{ .Values.adminUI.host }}-tls
  {{- end }}
  rules:
    - host: {{ .Values.adminUI.host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: admin-ui
              servicePort: web
{{ else }}
{{- if .Capabilities.APIVersions.Has "route.openshift.io/v1/Route" }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}-admin-ui-route
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/issuer: {{ .Release.Name }}-admin-ui
    {{ if hasKey .Values.certManager "dns01" -}}
    cert-manager.io/acme-challenge-type: "dns01"
    {{ else -}}
    cert-manager.io/acme-challenge-type: "http01"
    {{ end }}
  labels:
    {{- include "kre.labels" . | nindent 4 }}
    app: {{ .Release.Name }}-admin-ui-route
spec:
  host: {{ .Values.adminUI.host }}
  path: /  
  port:
    targetPort: web
  to:
    kind: Service
    name: admin-ui
    weight: 100
{{ else }}
{{ if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
apiVersion: networking.k8s.io/v1
{{ else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/Ingress" }}
apiVersion: networking.k8s.io/v1beta1
{{ else if .Capabilities.APIVersions.Has "extensions/v1beta1/Ingress" }}
apiVersion: extensions/v1beta1
{{ end }}
kind: Ingress
metadata:
  name: {{ .Release.Name }}-admin-ui-ingress
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: {{ .Release.Name }}-admin-ui
    {{ if hasKey .Values.certManager "dns01" -}}
    cert-manager.io/acme-challenge-type: "dns01"
    {{ else -}}
    cert-manager.io/acme-challenge-type: "http01"
    {{ end }}
  labels:
    {{- include "kre.labels" . | nindent 4 }}
    app: {{ .Release.Name }}-admin-ui-ingress
spec:
  {{- if .Values.adminUI.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.adminUI.host }}
      secretName: {{ .Values.adminUI.host }}-tls
  {{- end }}
  rules:
    - host: {{ .Values.adminUI.host }}
      http:
        paths:
          {{ if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: admin-ui
                port:
                  number: 80
          {{ else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/Ingress" }}
          - path: /
            backend:
              serviceName: admin-ui
              servicePort: web
          {{ end }} 
{{- end }}
{{ end }}
