apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-admin-ui-ingress
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: {{ .Release.Name }}-admin-ui
    {{ if hasKey .Values.certManager "dns01" -}}
    cert-manager.io/acme-challenge-type: "dns01"
    {{ else -}}
    cert-manager.io/acme-challenge-type: "http01"
    {{ end }}
  labels:
    {{- include "kre.labels" . | nindent 4 }}
    app: {{ .Release.Name }}-admin-ui-ingress
spec:
  {{- if .Values.adminUI.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.adminUI.host }}
      secretName: {{ .Values.adminUI.host }}-tls
  {{- end }}
  rules:
    - host: {{ .Values.adminUI.host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: admin-ui
              servicePort: web
