release-helm-chart:
  stage: semantic-release
  image: node:10
  before_script:
    - npm install -g semantic-release@15.14.0 semantic-release/github
  script:
    - semantic-release -t helm-chart-v\${version}
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always
      changes:
      - helm/**/*

release-helm-after-image:
  stage: semantic-release-helm
  image: node:10
  before_script:
    - npm install -g semantic-release@15.14.0 semantic-release/github
  script:
    - semantic-release -t helm-chart-v\${version} -b $CI_COMMIT_TAG

  rules:
    - if: '$CI_COMMIT_TAG != "" && $CI_COMMIT_TAG !~ /^helm-chart-v\d*.\d*.\d*$/'
      when: manual

generate-helm-chart:
  stage: build
  image: alpine:3.11
  variables:
    HELM_VERSION: v3.0.3
    CHART_RELEASER: 1.0.0-beta.1
  before_script:
    - apk add --update bash gettext coreutils curl
    - wget -q https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz -O - | tar -xzO linux-amd64/helm > /usr/local/bin/helm
    - chmod +x /usr/local/bin/helm
    - wget -q https://github.com/helm/chart-releaser/releases/download/v${CHART_RELEASER}/chart-releaser_${CHART_RELEASER}_linux_amd64.tar.gz -O - | tar -xzO cr > /usr/local/bin/cr
    - chmod +x /usr/local/bin/cr
    - helm repo add stable https://kubernetes-charts.storage.googleapis.com
    - helm plugin install https://github.com/chartmuseum/helm-push
    - helm repo add konstellation-ce https://${HELM_USER}:${HELM_PASSWD}@charts.konstellation.io
    - export ADMIN_API_IMAGE_TAG=$(./scripts/git_latest_tag.sh "admin-api")
    - export ADMIN_UI_IMAGE_TAG=$(./scripts/git_latest_tag.sh "admin-ui")
    - export K8S_MANAGER_IMAGE_TAG=$(./scripts/git_latest_tag.sh "k8s-manager")
    - ./scripts/replace_env_path.sh
  script:
    - export CHART_VERSION=${CI_COMMIT_TAG#helm-chart-v}
    - helm dep update helm/kre
    - helm package helm/kre --version $CHART_VERSION -d helm/kre/
    - helm push helm/kre/kre-${CHART_VERSION}.tgz konstellation-ce 
    - /usr/local/bin/cr upload -o konstellation-io -r kre -p ./helm/kre --token $GITHUB_TOKEN
    - /usr/local/bin/cr index -o konstellation-io -r kre -p ./helm/kre -c https://charts.konstellation.io -i helm/kre/index.yaml -p helm/kre
    - curl --request POST --header $NOTIFY_TOKEN $NOTIFY_URL$CI_COMMIT_TAG
  rules:
    - if: '$CI_COMMIT_TAG =~ /^helm-chart-v\d*.\d*.\d*$/'
      when: always
  artifacts:
    untracked: false
    expire_in: 30 days
    paths:
      - helm/kre/index.yaml
