{{ if .Capabilities.APIVersions.Has "apps/v1" }}
apiVersion: apps/v1
  {{ else if .Capabilities.APIVersions.Has "extensions/v1beta1" }}
apiVersion: extensions/v1beta1
  {{ end }}
kind: Deployment
metadata:
  name: chronograf
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "runtime.labels" . | nindent 6 }}
      app: chronograf
  template:
    metadata:
      labels:
        {{- include "runtime.labels" . | nindent 8 }}
        app: chronograf
    spec:
      containers:
        - name: chronograf
          image: "chronograf:1.8.4"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
              name: api
          volumeMounts:
            - name: data
              mountPath: /var/lib/chronograf
            - name: config
              mountPath: /usr/share/chronograf/resources
          env:
            - name: RESOURCES_PATH
              value: /usr/share/chronograf/resources
            - name: BASE_PATH
              value: /measurements/{{ .Release.Name }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: chronograf-pvc
        - name: config
          configMap:
            name: chronograf-config
