apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongo-express
  labels:
    {{- include "mongoExpress.labels" . | nindent 4}}
spec:
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
  selector:
    {{- include "mongoExpress.selectorLabels" . | nindent 4 }}
