apiVersion: v1
kind: Service
metadata:
  name: kre-nats
  labels:
    {{- include "nats.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "nats.selectorLabels" . | nindent 4}}
  ports:
    - name: client
      protocol: TCP
      port: {{ .Values.nats.client.port }}
    - name: monitor
      protocol: TCP
      port: 8222
    - name: metrics
      protocol: TCP
      port: 7777
